SET SERVEROUTPUT ON
SET ECHO ON
SET TIME ON
SPOOL 6_6_DBMS_UTILITY.log

CREATE OR REPLACE PROCEDURE proc1 IS
BEGIN 
    DBMS_OUTPUT.PUT_LINE('Running proc1');
    DBMS_OUTPUT.PUT_LINE(DBMS_UTILITY.FORMAT_CALL_STACK);
    RAISE NO_DATA_FOUND;
END;
/

CREATE OR REPLACE PROCEDURE proc2 IS
    l_str VARCHAR(30) := 'Calling proc1';
BEGIN
    DBMS_OUTPUT.PUT_LINE(l_str);
    proc1;
END;
/

CREATE OR REPLACE PROCEDURE proc3 IS
BEGIN
    DBMS_OUTPUT.PUT_LINE('Calling proc2');
    proc2;
EXCEPTION
    WHEN OTHERS
    THEN
        DBMS_OUTPUT.PUT_LINE('Error stack at top level:');
        DBMS_OUTPUT.PUT_LINE(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('Proc3 -> Proc2 -> Proc1 backtrace');
    proc3;
    DBMS_OUTPUT.PUT_LINE(DBMS_UTILITY.FORMAT_CALL_STACK);
END;
/
SPOOL OFF
