SET SERVEROUTPUT ON
SET ECHO ON
SET TIME ON
SPOOL 7_2_INTERVAL.log

CREATE OR REPLACE FUNCTION age (dob_in IN DATE)
    RETURN INTERVAL YEAR TO MONTH
IS
BEGIN
    RETURN (SYSDATE - dob_in) YEAR TO MONTH;
END;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('Age in years-months: ' || age(TO_DATE('1981-01-01', 'YYYY-MM-DD')));
END;
/

SPOOL OFF
